In [8]:
#for i in range(1,13):
    #print(i)

s="kazi omar sharif"
for c in s:
    print(c)
    

k
a
z
i
 
o
m
a
r
 
s
h
a
r
i
f


In [27]:
x=range(10)
y=[ i for i in x if i%2==0]
print(y)

z=[i+j for i in range(10) for j in range(2)]
print(z)

x={"one":1,"two":2,"three":3}
{key:v**3 for (key,v) in x.items()}

[0, 2, 4, 6, 8]
[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10]


{'one': 1, 'two': 8, 'three': 27}

In [40]:
import sys
import numpy as np

sys.float_info
np.spacing(1e9)
max=(2**(2046-1023))*(1+sum(.5**np.arange(1,53)))
min=2**(1-1023)*(1+0)
print(f"max={max}\n min={min}")
sys.float_info.max
print(np.spacing(5*1e15))

max=1.7976931348623157e+308
 min=2.2250738585072014e-308
1.0


In [53]:
import numpy as np
from scipy import linalg

A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])

b=np.array([1,2,3])
x=linalg.solve(A,b)

A_inv=linalg.inv(A)
y=np.dot(A_inv,b)

P, L, U = linalg.lu(A)
y=linalg.solve_triangular(L,P.dot(b),lower=True)
solve=linalg.solve_triangular(U,y)
print(f"solve={solve}")
#print(f"P={P} \n L={L} \n U={U}")
#print(x)
#print(f"A={A}\t\n A^-1={A_inv}")
#print(y)

solve=[2.5 4.  3.5]
[1.         2.5        4.66666667]


In [61]:
B=np.random.rand(4,3)

print(f"B={B}")

B_pinv=np.linalg.pinv(B)
print(f"1.pseudo inverse of B={B_pinv}")

B_pinv2=np.linalg.inv(B.T @ B) @ B.T 

print(f"2.pseudo inverse of B={B_pinv2}")



B=[[0.14659869 0.19778106 0.04312539]
 [0.5262752  0.25477173 0.94243162]
 [0.27341171 0.91388988 0.65164077]
 [0.30853227 0.5867649  0.16505055]]
1.pseudo inverse of B=[[ 1.71057424  1.10471085 -2.38371169  2.65639903]
 [ 0.04620988 -0.79483532  1.04265836  0.40985275]
 [-0.93258967  0.65757053  1.05365434 -1.61224001]]
2.pseudo inverse of B=[[ 1.71057424  1.10471085 -2.38371169  2.65639903]
 [ 0.04620988 -0.79483532  1.04265836  0.40985275]
 [-0.93258967  0.65757053  1.05365434 -1.61224001]]


In [62]:
import math

num = 3.14159

mantissa, exponent = math.frexp(num)

print("Mantissa:", mantissa)
print("Exponent:", exponent)


Mantissa: 0.7853975
Exponent: 2
